import { ICard } from "./helpers/interfaces";

const data: Array<ICard> = [ 
  {
    id: 1,
    title: 'Assam Enigma',
    img: './img/assam.jpg',
    country: 'India',
    year: 2022,
    season: 'Summer',
    variety: 'Black',
    stock: 12,
    favorite: 'yes',
    price: 9
  },
  {
    id: 2,
    title: 'Gold Ceylon',
    img: './img/ceylon.jpg',
    country: 'Ceylon',
    year: 2022,
    season: 'Summer',
    variety: 'Black',
    stock: 6,
    favorite: 'no',
    price: 7.5
  },
  {
    id: 3,
    title: 'Da Hong Pao',
    img: './img/da-hong-pao.jpg',
    country: 'China',
    year: 2021,
    season: 'Fall',
    variety: 'Oolong',
    stock: 5,
    favorite: 'yes',
    price: 17
  },
  {
    id: 4,
    title: 'Jin Jun Mei',
    img: './img/jin-jun-mei.jpg',
    country: 'China',
    year: 2021,
    season: 'Summer',
    variety: 'Black',
    stock: 8,
    favorite: 'yes',
    price: 16.5
  },
  {
    id: 5,
    title: 'Long Jing',
    img: './img/long-jing.jpg',
    country: 'China',
    year: 2022,
    season: 'Spring',
    variety: 'Green',
    stock: 18,
    favorite: 'yes',
    price: 28
  },
  {
    id: 6,
    title: 'Organic Dargeeling',
    img: './img/organic-darjeeling.jpg',
    country: 'India',
    year: 2021,
    season: 'Fall',
    variety: 'Black',
    stock: 13,
    favorite: 'yes',
    price: 21
  },
  {
    id: 7,
    title: 'Ripe Puerh',
    img: './img/puerh-ripe.jpg',
    country: 'China',
    year: 2015,
    season: 'Fall',
    variety: 'Puerh',
    stock: 7,
    favorite: 'no',
    price: 12
  },
  {
    id: 8,
    title: 'Shen Puerh',
    img: './img/puerh-shen.jpg',
    country: 'China',
    year: 2012,
    season: 'Winter',
    variety: 'Puerh',
    stock: 2,
    favorite: 'yes',
    price: 39
  },
  {
    id: 9,
    title: 'Tai Ping Hou Kui',
    img: './img/tai-ping-hou-kui.jpg',
    country: 'China',
    year: 2021,
    season: 'Spring',
    variety: 'Green',
    stock: 12,
    favorite: 'yes',
    price: 19
  },
  {
    id: 10,
    title: 'Tie Guan Yin',
    img: './img/tie-guan-yin.jpg',
    country: 'China',
    year: 2022,
    season: 'Spring',
    variety: 'Oolong',
    stock: 16,
    favorite: 'yes',
    price: 15
  },
  {
    id: 11,
    title: 'Darjeeling - First Flush',
    img: './img/darjeeling-first-flush.jpeg',
    country: 'India',
    year: 2022,
    season: 'Spring',
    variety: 'Black',
    stock: 16,
    favorite: 'yes',
    price: 23
  },
  {
    id: 12,
    title: 'Bai Hao Yin Zhen',
    img: './img/bai-hao-yin-zhen.jpg',
    country: 'China',
    year: 2022,
    season: 'Spring',
    variety: 'White',
    stock: 6,
    favorite: 'yes',
    price: 49
  },
  {
    id: 13,
    title: 'Bai Mu Dan',
    img: './img/bai-mu-dan.jpg',
    country: 'China',
    year: 2022,
    season: 'Fall',
    variety: 'White',
    stock: 14,
    favorite: 'yes',
    price: 36
  },
  {
    id: 14,
    title: 'English Breakfast',
    img: './img/english-breakfast.jpg',
    country: 'India',
    year: 2020,
    season: 'Summer',
    variety: 'Black',
    stock: 12,
    favorite: 'no',
    price: 5
  },
  {
    id: 15,
    title: 'Ceylon Green Tea',
    img: './img/ceylon-green-tea.jpg',
    country: 'Ceylon',
    year: 2021,
    season: 'Spring',
    variety: 'Green',
    stock: 17,
    favorite: 'no',
    price: 16
  },
  {
    id: 16,
    title: 'Bi Luo Chun',
    img: './img/bi-luo-chun.jpg',
    country: 'China',
    year: 2022,
    season: 'Spring',
    variety: 'Green',
    stock: 12,
    favorite: 'yes',
    price: 21
  },
  {
    id: 17,
    title: 'Dian Hong',
    img: './img/dian-hong.jpg',
    country: 'China',
    year: 2021,
    season: 'Summer',
    variety: 'Black',
    stock: 17,
    favorite: 'no',
    price: 17
  },
  {
    id: 18,
    title: 'Alishan',
    img: './img/alishan.jpeg',
    country: 'China',
    year: 2021,
    season: 'Spring',
    variety: 'Oolong',
    stock: 15,
    favorite: 'yes',
    price: 39
  },
  {
    id: 19,
    title: 'Shui Xian',
    img: './img/shui-xian.jpg',
    country: 'China',
    year: 2021,
    season: 'Summer',
    variety: 'Oolong',
    stock: 7,
    favorite: 'no',
    price: 24
  },
  {
    id: 20,
    title: 'Rou Gui',
    img: './img/rou-gui.jpeg',
    country: 'China',
    year: 2020,
    season: 'Summer',
    variety: 'Oolong',
    stock: 4,
    favorite: 'no',
    price: 12
  },
  {
    id: 21,
    title: 'Shou Mei',
    img: './img/shou-mei.jpg',
    country: 'China',
    year: 2021,
    season: 'Fall',
    variety: 'White',
    stock: 1,
    favorite: 'no',
    price: 19
  }
]

export default data;